# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 273)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ProgressBar.setGeometry(QtCore.QRect(10, 180, 321, 23))
        self.ProgressBar.setMaximum(100)
        self.ProgressBar.setProperty("value", 100)
        self.ProgressBar.setObjectName("ProgressBar")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 211, 80))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setStyleSheet("backgroud-color: rgb(255, 255, 255)")
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_ptotal = QtWidgets.QLabel(self.groupBox)
        self.label_ptotal.setGeometry(QtCore.QRect(10, 10, 191, 16))
        self.label_ptotal.setObjectName("label_ptotal")
        self.label_psec = QtWidgets.QLabel(self.groupBox)
        self.label_psec.setGeometry(QtCore.QRect(10, 30, 191, 16))
        self.label_psec.setStyleSheet("")
        self.label_psec.setObjectName("label_psec")
        self.label_auto = QtWidgets.QLabel(self.groupBox)
        self.label_auto.setGeometry(QtCore.QRect(10, 50, 191, 16))
        self.label_auto.setObjectName("label_auto")
        self.label_ctotal = QtWidgets.QLabel(self.centralwidget)
        self.label_ctotal.setGeometry(QtCore.QRect(230, 0, 101, 31))
        self.label_ctotal.setObjectName("label_ctotal")
        self.Button_shop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_shop.setGeometry(QtCore.QRect(234, 42, 91, 41))
        self.Button_shop.setObjectName("Button_shop")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(10, 210, 75, 23))
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(260, 210, 75, 23))
        self.load.setObjectName("load")
        self.label_lvl = QtWidgets.QLabel(self.centralwidget)
        self.label_lvl.setGeometry(QtCore.QRect(136, 210, 61, 16))
        self.label_lvl.setObjectName("label_lvl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar_shop = QtWidgets.QMenuBar(MainWindow)
        self.menubar_shop.setGeometry(QtCore.QRect(0, 0, 345, 21))
        self.menubar_shop.setObjectName("menubar_shop")
        MainWindow.setMenuBar(self.menubar_shop)
        self.statusbar_lvl = QtWidgets.QStatusBar(MainWindow)
        self.statusbar_lvl.setObjectName("statusbar_lvl")
        MainWindow.setStatusBar(self.statusbar_lvl)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clicker"))
        self.pushButton.setText(_translate("MainWindow", "Нажми меня"))
        self.label_ptotal.setText(_translate("MainWindow", "Всего очков:"))
        self.label_psec.setText(_translate("MainWindow", "Кликов в секунду:"))
        self.label_auto.setText(_translate("MainWindow", "Автозароботок:"))
        self.label_ctotal.setText(_translate("MainWindow", "Кликов сделано:"))
        self.Button_shop.setText(_translate("MainWindow", "Магазин"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.load.setText(_translate("MainWindow", "Загрузить"))
        self.label_lvl.setText(_translate("MainWindow", "Уровень 1"))
